version: 2

jobs:
  # Build & Deploy against development backend rer
  "build-dev":
    docker:
      - image: - image: circleci/node:8.10
    steps:
      # Initialization.
      - checkout
      - run:
          name: Installation of build dependencies.
          command: apk add --no-cache bash

      # Restoration of node_modules from cache.
      - restore_cache:
          key: docker-tc-bus-api-{{ checksum "package-lock.json" }}

      - run:
          name: Install Serverless CLI and AWS CLI
          command: |
            sudo npm i -g serverless
            npm install    
            apk add --no-cache jq py-pip sudo
            sudo pip install awscli --upgrade

      # Build of Docker image.
      - run:
          name: Build of Docker image
          command: ./build.sh DEV

        # deploy app            
      - run:
          name: Deploy application 
          command: sls deploy -v    

      # Caching node modules.
      - save_cache:
          key: docker-tc-bus-api-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            

workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          filters:
            branches:
              only: ['dev', 'lambda-testing']
      - "build-prod":
          filters:
            branches:
              only: master
