version: 2

jobs:
  # Build & Deploy against development backend rer
  "build-dev":
    docker:
      - image: circleci/node:8.10
    steps:
      # Initialization.
      - checkout

      # Restoration of node_modules from cache.
      - restore_cache:
          key: docker-tc-bus-api-{{ checksum "package-lock.json" }}

      - run:
          name: Install Serverless CLI and AWS CLI
          command: |
            sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
            curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
            #install awscli
            sudo pip install awscli --upgrade
            #install serverless
            sudo npm install -g try-thread-sleep
            sudo npm install -g serverless --ignore-scripts spawn-sync
            #install ruamerl
            sudo python -m pip install ruamel.yaml --user
            #install yq
            #sudo apt install yq -y
            sudo pip install yq
            npm install    
      # Caching node modules.
      - save_cache:
          key: docker-tc-bus-api-{{ checksum "package-lock.json" }}
          paths:
            - node_modules     

        # deploy app            
      - run:
          name: Deploy via Masterscript v2
          command: |
             git clone --branch master https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
             cp ./../buildscript/master_deply_v4.2.sh .
             ./master_deply_v4.2.sh -d LAMBDA -e DEV -s bus-lambda-env  
            
workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          filters:
            branches:
              only: ['dev', 'lambda-testing']
      - "build-prod":
          filters:
            branches:
              only: master
